services:


  vlt-core-db:
    container_name: vlt-core-db
    image: postgres:17.4
    restart: on-failure
    environment:
      POSTGRES_DB: core_db
      POSTGRES_USER: ${CORE_DB_USERNAME}
      POSTGRES_PASSWORD: ${CORE_DB_PASSWORD}
    volumes:
      - core_db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${CORE_DB_USERNAME} -h localhost -p ${CORE_DB_PASSWORD} -d core_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      vlt:

volumes:
  core_db_data:

networks:
  vlt:
    external: true